/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect4;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.io.*;
import java.util.Collections;
import javax.swing.JOptionPane;
/**
 *
 * @author Devrajsinh Bhati
 * August 21st, 2018
 * This frame allows the client's students to register their names into the StudentInfo.txt file 
 */
public class RegisterApp extends javax.swing.JFrame {

    /**
     * Creates new form RegisterApp
     */
    public RegisterApp() {
        initComponents();
    }
    
    //Method to close JFrame
    public void close(){
        WindowEvent CloseFrame = new WindowEvent (this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(CloseFrame);
    }
    
    //ArrayList holding Student information using the Student object class 
    ArrayList <Student> ArrStudentInfo = new ArrayList <Student>();
    
    //Variable to store student grade in sentence form
    String strStudentGrade;
    
    //Creating Student object class to store student information
    class Student{
        String strName,strGrade, strAge;
        
        //Constructor
        public Student(String _strName, String _strGrade, String _strAge){
            strName = _strName;
            strGrade = _strGrade;
            strAge = _strAge;
        }
    }

    //Method which checks to see if student name is already registered into the ArrayList
    /**
     * 
     * @param strFind as the name of the student registering 
     * @param intArrayIndex as the index of the element being compared to strFind
     * @return 
     */
    //**This method is done recursively**
    
    public int LinearSearch(String strFind, int intArrayIndex){
               
        if (intArrayIndex > ArrStudentInfo.size()-1){
            return 1; //Meaning not found
            
        }
        System.out.println(ArrStudentInfo.get(intArrayIndex).strName + " " + strFind);
        
        if (ArrStudentInfo.get(intArrayIndex).strName.equals(strFind)){//Found that student's name is already registered
            return 0;
            
        }
        else return LinearSearch(strFind, intArrayIndex + 1);
        
    }
    
    /**
     * This method helps store user's grade in sentence form
     * @param intGrade as the grade selected by the user
     * @return a String indicating their grade in sentence form
     */
    public String GradeOutput(int intGrade){
        switch(intGrade){
            case 1: return "This student is in Grade 1.";
 
            case 2: return "This student is in Grade 2.";
            
            case 3: return "This student is in Grade 3.";
            
            case 4: return "This student is in Grade 4.";
            
            case 5: return "This student is in Grade 5.";
        }
        return "N/A";
    }
    /**
     * This method is called from within the constructor to
     * initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGrade = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblFirst = new javax.swing.JLabel();
        lblLast = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        scrlPanelRegisterInfo = new javax.swing.JScrollPane();
        txtAreaRegisterInfo = new javax.swing.JTextArea();
        txtFirst = new javax.swing.JTextField();
        txtLast = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnGrade1 = new javax.swing.JRadioButton();
        btnGrade2 = new javax.swing.JRadioButton();
        btnGrade3 = new javax.swing.JRadioButton();
        btnGrade4 = new javax.swing.JRadioButton();
        btnGrade5 = new javax.swing.JRadioButton();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(153, 153, 255));

        lblTitle.setFont(new java.awt.Font("Palatino Linotype", 1, 30)); // NOI18N
        lblTitle.setText("Register");

        lblFirst.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblFirst.setText("First Name:");

        lblLast.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblLast.setText("Last Name:");

        lblGrade.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblGrade.setText("Select Grade:");

        lblAge.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblAge.setText("Age:");

        txtAreaRegisterInfo.setEditable(false);
        txtAreaRegisterInfo.setColumns(20);
        txtAreaRegisterInfo.setLineWrap(true);
        txtAreaRegisterInfo.setRows(5);
        txtAreaRegisterInfo.setText("Hello students! Your teacher would like to keep track of who is playing the Connect 4 game. Please fill out the form below.\n\n     *You can still play the game without registering* ");
        txtAreaRegisterInfo.setWrapStyleWord(true);
        scrlPanelRegisterInfo.setViewportView(txtAreaRegisterInfo);

        txtFirst.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtLast.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtLast.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnGrade1.setBackground(new java.awt.Color(153, 153, 255));
        btnGroupGrade.add(btnGrade1);
        btnGrade1.setText("Grade 1");
        btnGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrade1ActionPerformed(evt);
            }
        });

        btnGrade2.setBackground(new java.awt.Color(153, 153, 255));
        btnGroupGrade.add(btnGrade2);
        btnGrade2.setText("Grade 2");
        btnGrade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrade2ActionPerformed(evt);
            }
        });

        btnGrade3.setBackground(new java.awt.Color(153, 153, 255));
        btnGroupGrade.add(btnGrade3);
        btnGrade3.setText("Grade 3");
        btnGrade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrade3ActionPerformed(evt);
            }
        });

        btnGrade4.setBackground(new java.awt.Color(153, 153, 255));
        btnGroupGrade.add(btnGrade4);
        btnGrade4.setText("Grade 4");
        btnGrade4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrade4ActionPerformed(evt);
            }
        });

        btnGrade5.setBackground(new java.awt.Color(153, 153, 255));
        btnGroupGrade.add(btnGrade5);
        btnGrade5.setText("Grade 5 ");
        btnGrade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrade5ActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(lblTitle))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(scrlPanelRegisterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(lblFirst)
                                .addGap(18, 18, 18)
                                .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(lblGrade)
                                .addGap(18, 18, 18)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGrade2)
                                    .addComponent(btnGrade1)
                                    .addComponent(btnGrade3)
                                    .addComponent(btnGrade4)
                                    .addComponent(btnGrade5))))
                        .addGap(31, 31, 31)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(lblLast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRegister)
                                .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                    .addComponent(lblAge)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlPanelRegisterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirst)
                    .addComponent(lblLast)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(btnRegister))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGrade1)
                            .addComponent(lblGrade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGrade2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGrade3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGrade4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGrade5)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrade1ActionPerformed
        // TODO add your handling code here:
        strStudentGrade = GradeOutput(1);
    }//GEN-LAST:event_btnGrade1ActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        Student newStudent;
        
        //Storing user input
        String strFirst = this.txtFirst.getText();
        String strLast = this.txtLast.getText();
        String strAge = this.txtAge.getText();
        String strFull = strFirst + " " + strLast;
        //Creating new object in Student class
        newStudent = new Student(strFull, strStudentGrade, strAge);
             
        
        
        //Only modifies txt file if a new student is registering 
        if (LinearSearch(strFull, 0) == 1){
        System.out.println(ArrStudentInfo.size());
        ArrStudentInfo.add(newStudent);
        System.out.println(ArrStudentInfo.size());
        
        try
        {
            FileWriter WriteF = new FileWriter("src/connect4/StudentInfo.txt", true);           
            PrintWriter PrintF = new PrintWriter(WriteF);
            
            //Will print all the student information stored in the ArrayList into the StudentInfo.txt file
            //After running the program and registering, you can open the txt file to see that it has been modified
            
            for (int i = 0; i < ArrStudentInfo.size (); i++){
                PrintF.println (ArrStudentInfo.get(i).strName); 
                PrintF.println ("Age: " + ArrStudentInfo.get(i).strAge);
                PrintF.println(ArrStudentInfo.get(i).strGrade);
                PrintF.println();
            }                               
            
                PrintF.close();
        }
        catch (IOException e){}
               
        }
        
        else if (LinearSearch(strFull, 0) == 0){
            
            JOptionPane.showMessageDialog (null, "This student is already registered.", "Student Already Exists", JOptionPane.INFORMATION_MESSAGE);                     
        }    
                
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnGrade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrade2ActionPerformed
        // TODO add your handling code here:
        strStudentGrade = GradeOutput(2);
    }//GEN-LAST:event_btnGrade2ActionPerformed

    private void btnGrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrade3ActionPerformed
        // TODO add your handling code here:
        strStudentGrade = GradeOutput(3);
    }//GEN-LAST:event_btnGrade3ActionPerformed

    private void btnGrade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrade4ActionPerformed
        // TODO add your handling code here:
        strStudentGrade = GradeOutput(4);
    }//GEN-LAST:event_btnGrade4ActionPerformed

    private void btnGrade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrade5ActionPerformed
        // TODO add your handling code here:
        strStudentGrade = GradeOutput(5);
    }//GEN-LAST:event_btnGrade5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnGrade1;
    private javax.swing.JRadioButton btnGrade2;
    private javax.swing.JRadioButton btnGrade3;
    private javax.swing.JRadioButton btnGrade4;
    private javax.swing.JRadioButton btnGrade5;
    private javax.swing.ButtonGroup btnGroupGrade;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JScrollPane scrlPanelRegisterInfo;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextArea txtAreaRegisterInfo;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    // End of variables declaration//GEN-END:variables
}
